version: '3'
services:
  ansible-master:
    build: .
    container_name: ansible-master
    hostname: master
    networks:
      - ansible-net

  node1:
    build: .
    container_name: node1
    hostname: node1
    networks:
      - ansible-net

  node2:
    build: .
    container_name: node2
    hostname: node2
    networks:
      - ansible-net

networks:
  ansible-net:

