apiVersion: v1
kind: Pod
metadata:
  name: ansible-master
  labels:
    role: master
spec:
  containers:
  - name: master
    image: ubuntu:22.04
    command: ["/bin/bash", "-c"]
    args:
      - |
        apt-get update && \
        apt-get install -y openssh-server sudo python3 python3-pip software-properties-common vim && \
        add-apt-repository --yes --update ppa:ansible/ansible && \
        apt-get install -y ansible && \
        useradd -m ansible && echo "ansible:ansible" | chpasswd && \
        echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
        mkdir /var/run/sshd && \
        /usr/sbin/sshd -D
    ports:
    - containerPort: 22
